server:
  port: 2230
spring:
  application:
    name: mysql-service
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springstudy?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: yf970708

#Mapper.xml所在的位置
mybatis:
  mapper-locations: classpath:/*.xml

#配置redis数据库连接
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
    max-idle: 20
    min-idle: 1
    max-active: 20
    max-wait: 60000
    database: 0 #默认是索引为0的数据库


#pagehelper分页插件配置
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql

info:
 app:
  name: spring-boot-hello
  version: v1.0.0
  #服务跟踪
#  zipkin:
#    enabled: true
#    base-url: http://10.16.8.97:9411
#  sleuth:
#    sampler:
#      percentage: 1.0






eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
            defaultZone: http://127.0.0.1:1111/eureka/
#            defaultZone: http://10.236.128.226:1111/eureka/
endpoints:
  shutdown:
    enabled: true
    sensitive: false
  restart:
    enabled: true
    sensitive: false
  trace:
    enabled: true
    sensitive: false
  dump:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
  logfile:
    enabled: true
    sensitive: false
  configprops:
    enabled: true
    sensitive: false

security:
  basic:
    enabled: false
management:
  security:
    enabled: false









